require("dotenv").config();
const express = require("express");
const cors = require("cors");
const authRoutes = require("./routes/auth");
const professionalRoutes = require("./routes/professionals");
const agreementRoutes = require("./routes/agreements");
const dashboardRoutes = require("./routes/dashboard");
const membershipRoutes = require("./routes/membership");
const app = express();
app.use(cors());
app.use(express.json());
app.get("/health", (req,res)=>res.json({ok:true}));
app.use("/auth", authRoutes);
app.use("/professionals", professionalRoutes);
app.use("/agreements", agreementRoutes);
app.use("/dashboard", dashboardRoutes);
app.use("/membership", membershipRoutes);
const PORT=process.env.PORT||4000;
app.listen(PORT,()=>console.log(`Vakalat API listening on :${PORT}`));
